# Generated by Django 3.0.2 on 2020-05-21 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
